version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  php:
    build:
      context: .
      target: app_php
    image: docker/php:dev
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    depends_on:
      - postgres
    volumes:
      - .:/app:rw,cached

  nginx:
    build:
      context: .
      target: app_nginx
    image: docker/nginx:dev
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./public:/app/public:ro
    ports:
      - "8080:80"